name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

env:
  NODE_VERSION: 14.15.3-alpine3.12
  PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64/v8

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker strapi base meta
        id: docker_base_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          tag-sha: true
          tag-custom: bertpersyn/strapi-base:${{ env.NODE_VERSION }}
          tag-custom-only: true
      -
        name: Docker strapi meta
        id: docker_strapi_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: bertpersyn/strapi
          tag-sha: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push base
        id: docker_base_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base/alpine/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_base_meta.outputs.tags }}
          labels: ${{ steps.docker_base_meta.outputs.labels }}
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
      -
        name: Build and push strapi
        id: docker_strapi_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./strapi/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_strapi_meta.outputs.tags }}
          labels: ${{ steps.docker_strapi_meta.outputs.labels }}
          build-args: |
            BASE_VERSION=${{ env.NODE_VERSION }}
            STRAPI_VERSION=${{ steps.docker_strapi_meta.outputs.version }}
